powershell -Command "Set-NetOffloadGlobalSetting -Chimney Disabled"
powershell -Command "Set-NetOffloadGlobalSetting -NetworkDirect Disabled"
powershell -Command "Set-NetOffloadGlobalSetting -NetworkDirectAcrossIPSubnets Blocked"
powershell -Command "Set-NetOffloadGlobalSetting -PacketCoalescingFilter Disabled"
powershell -Command "Set-NetOffloadGlobalSetting -ReceiveSegmentCoalescing Disabled"
powershell -Command "Set-NetOffloadGlobalSetting -ReceiveSideScaling Disabled"
powershell -Command "Set-NetOffloadGlobalSetting -TaskOffload Disabled"

powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_msclient'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_implat'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_pacer'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_server'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_lldp'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_tcpip6'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_rspndr'"
powershell -Command "Disable-NetAdapterBinding -Name '*' -ComponentID 'ms_lltdio'"

powershell -Command "netsh interface 6to4 set state disabled undoonstop=enabled"
powershell -Command "netsh interface isatap set state disabled"
powershell -Command "netsh interface teredo set state disabled"
powershell -Command "netsh winsock set autotuning off"
powershell -Command "netsh interface udp set global uro=disabled"
powershell -Command "netsh interface udp set global uso=disabled"

powershell -Command "Set-NetTCPSetting -SettingName Datacenter"
powershell -Command "Set-NetTCPSetting -AutoTuningLevelLocal Disabled"
powershell -Command "Set-NetTCPSetting -AutomaticUseCustom Enabled"
powershell -Command "Set-NetTCPSetting -CongestionProvider CTCP"
powershell -Command "Set-NetTCPSetting -CwndRestart True"
powershell -Command "Set-NetTCPSetting -DelayedAckFrequency 1"
powershell -Command "Set-NetTCPSetting -DelayedAckTimeoutMs 10"
powershell -Command "Set-NetTCPSetting -EcnCapability Disabled"
powershell -Command "Set-NetTCPSetting -ForceWS Disabled"
powershell -Command "Set-NetTCPSetting -InitialCongestionWindowMss 2"
powershell -Command "Set-NetTCPSetting -InitialRtoMs 300"
powershell -Command "Set-NetTCPSetting -MaxSynRetransmissions 2"
powershell -Command "Set-NetTCPSetting -MemoryPressureProtection Disabled"
powershell -Command "Set-NetTCPSetting -MinRtoMs 20"
powershell -Command "Set-NetTCPSetting -NonSackRttResiliency Enabled"
powershell -Command "Set-NetTCPSetting -ScalingHeuristics Disabled"
powershell -Command "Set-NetTCPSetting -Timestamps Disabled"

powershell -Command "Set-NetIPInterface -AdvertiseDefaultRoute Disabled"
powershell -Command "Set-NetIPInterface -Advertising Disabled"
powershell -Command "Set-NetIPInterface -AutomaticMetric Enabled"
powershell -Command "Set-NetIPInterface -BaseReachableTimeMs 15"
powershell -Command "Set-NetIPInterface -ClampMss Disabled"
powershell -Command "Set-NetIPInterface -CurrentHopLimit 64"
powershell -Command "Set-NetIPInterface -DadRetransmitTimeMs 1000"
powershell -Command "Set-NetIPInterface -DadTransmits 1"
powershell -Command "Set-NetIPInterface -DirectedMacWolPattern Disabled"
powershell -Command "Set-NetIPInterface -EcnMarking AppDecide"
powershell -Command "Set-NetIPInterface -ForceArpNdWolPattern Disabled"
powershell -Command "Set-NetIPInterface -Forwarding Disabled"
powershell -Command "Set-NetIPInterface -IgnoreDefaultRoutes Disabled"
powershell -Command "Set-NetIPInterface -ManagedAddressConfiguration Enabled"
powershell -Command "Set-NetIPInterface -NeighborDiscoverySupported Yes"
powershell -Command "Set-NetIPInterface -NeighborUnreachabilityDetection Enabled"
powershell -Command "Set-NetIPInterface -NlMtuBytes 1500"
powershell -Command "Set-NetIPInterface -OtherStatefulConfiguration Disabled"
powershell -Command "Set-NetIPInterface -PolicyStore ActiveStore"
powershell -Command "Set-NetIPInterface -ReachableTime 1000"
powershell -Command "Set-NetIPInterface -RetransmitTimeMs 500"
powershell -Command "Set-NetIPInterface -RouterDiscovery Enabled"
powershell -Command "Set-NetIPInterface -WeakHostReceive Disabled"
powershell -Command "Set-NetIPInterface -WeakHostSend Disabled"

powershell -Command "Set-NetIPv4Protocol -AddressMaskReply Disabled"
powershell -Command "Set-NetIPv4Protocol -DeadGatewayDetection Disabled"
powershell -Command "Set-NetIPv4Protocol -DefaultHopLimit 64"
powershell -Command "Set-NetIPv4Protocol -DhcpMediaSense Disabled"
powershell -Command "Set-NetIPv4Protocol -GroupForwardedFragments Disabled"
powershell -Command "Set-NetIPv4Protocol -IGMPLevel None"
powershell -Command "Set-NetIPv4Protocol -IGMPVersion Version3"
powershell -Command "Set-NetIPv4Protocol -IcmpRedirects Disabled"
powershell -Command "Set-NetIPv4Protocol -MediaSenseEventLog Disabled"
powershell -Command "Set-NetIPv4Protocol -MinimumMtu 4294967295"
powershell -Command "Set-NetIPv4Protocol -MulticastForwarding Disabled"
powershell -Command "Set-NetIPv4Protocol -NeighborCacheLimitEntries 256"
powershell -Command "Set-NetIPv4Protocol -RandomizeIdentifiers Disabled"
powershell -Command "Set-NetIPv4Protocol -ReassemblyLimitBytes 8192"
powershell -Command "Set-NetIPv4Protocol -RouteCacheLimitEntries 128"
powershell -Command "Set-NetIPv4Protocol -SourceRoutingBehavior Drop"

powershell -Command "Set-NetIPv6Protocol -AddressMaskReply Disabled"
powershell -Command "Set-NetIPv6Protocol -DeadGatewayDetection Disabled"
powershell -Command "Set-NetIPv6Protocol -DefaultHopLimit 128"
powershell -Command "Set-NetIPv6Protocol -DhcpMediaSense Disabled"
powershell -Command "Set-NetIPv6Protocol -GroupForwardedFragments Disabled"
powershell -Command "Set-NetIPv6Protocol -IcmpRedirects Disabled"
powershell -Command "Set-NetIPv6Protocol -MediaSenseEventLog Disabled"
powershell -Command "Set-NetIPv6Protocol -MldLevel None"
powershell -Command "Set-NetIPv6Protocol -MldVersion Version2"
powershell -Command "Set-NetIPv6Protocol -MulticastForwarding Disabled"
powershell -Command "Set-NetIPv6Protocol -NeighborCacheLimitEntries 256"
powershell -Command "Set-NetIPv6Protocol -RandomizeIdentifiers Disabled"
powershell -Command "Set-NetIPv6Protocol -ReassemblyLimitBytes 8192"
powershell -Command "Set-NetIPv6Protocol -RouteCacheLimitEntries 128"
powershell -Command "Set-NetIPv6Protocol -SourceRoutingBehavior Drop"
powershell -Command "Set-NetIPv6Protocol -UseTemporaryAddresses Disabled"

powershell -Command "Disable-NetAdapterChecksumOffload -Name '*'"
powershell -Command "Disable-NetAdapterLso -Name '*'"
powershell -Command "Disable-NetAdapterPowerManagement -Name '*'"
powershell -Command "Disable-NetAdapterQos -Name '*'"
powershell -Command "Disable-NetAdapterRdma -Name '*'"
powershell -Command "Disable-NetAdapterRsc -Name '*'"
powershell -Command "Disable-NetAdapterRss -Name '*'"
powershell -Command "Set-NetAdapterRss -Name '*' -IncludeHidden -BaseProcessorGroup 0 -BaseProcessorNumber 1 -Enabled 0 -MaxProcessorGroup 0 -MaxProcessorNumber 1 -MaxProcessors 1 -NumaNode 0 -NumberOfReceiveQueues 1 -Profile Conservative"
powershell -Command "Disable-NetAdapterSriov -Name '*'"
powershell -Command "Disable-NetAdapterUso -Name '*'"
powershell -Command "Disable-NetAdapterVmq -Name '*'"

powershell -Command "Set-NetAdapterDataPathConfiguration -Name '*' -IncludeHidden -Profile Dispatch"

pause
